---
#InputsConfig.yaml

- Inputs :
  - InputsManager :
    - Move :
    - Look :

  - InputsEvents :
# Keyboard
    - Move :
      MoveForward: "Z"
      MoveBackward: "S"
      MoveRight: "D"
      MoveLeft: "Q"
      MoveUp: "E"
      MoveDown: "A"

# Mouse
    - Look :
      Position :
        x : 0
        y : 0
      DeltaMovement :
        x : 0
        y : 0
      DeltaScroll :
        x : 0
        y : 0